spring:
  application:
    name: kafka-consumer
  kafka:
    consumer:
      group-id: example-group
      auto-offset-reset: earliest

app:
  kafka:
    topics:
      - test-topic
      - notifications
      - orders
      - emails

server:
  port: 8081